version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.module:jackson-module-kotlin
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.auth0:java-jwt
    versions:
    - 3.12.1
    - 3.13.0
    - 3.14.0
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
  - dependency-name: io.github.microutils:kotlin-logging
    versions:
    - 2.0.4
  - dependency-name: junit:junit
    versions:
    - 4.13.1
